input LoginInput {
  email: String!
  password: String!
}

input SignupInput {
  type: Int!
  firstName: String!
  lastName: String!
  email: String!
  password: String!
}

input VerifyAccountInput {
  token: String!
}

input ForgottenPassword {
  email: String!
}

input ResetPasswordInput {
  token: String!
  password: String!
}

type Account {
  _id: ID
  firstName: String
  lastName: String
  roles: [String]
}

type AuthAccount {
  account: Account
  token: String
}

type Query {
  currentAccountInfo: Account @auth(role: USER)
}

type Mutation {
  login(input: LoginInput!): AuthAccount
  signup(input: SignupInput!): Account
  verifyAccount(input: VerifyAccountInput!): Boolean
  forgottenPassword(input: ForgottenPassword): Boolean
  resetPassword(input: ResetPasswordInput): Boolean
}