type Carbohydrates {
  fiber: Float
  sugar: Float
}

type Fats {
  monounsaturated: Float
  polyunsaturated: Float
  saturated: Float
}

type Nutrients {
  carbohydrate: Carbohydrates
  cholesterol: Float
  fat: Fats
  potassium: Float
  protein: Float
  sodium: Float
}

type Ingredient {
  id: ID
  name: String!
  calories: Int
  nutrients: Nutrients
}

input CarbohydratesInput {
  fiber: Float
  sugar: Float
}

input FatsInput {
  monounsaturated: Float
  polyunsaturated: Float
  saturated: Float
}

input NutrientsInput {
  carbohydrate: CarbohydratesInput
  cholesterol: Float
  fat: FatsInput
  potassium: Float
  protein: Float
  sodium: Float
}

input IngredientCreateInput {
  name: String!
  category: ID
  calories: Int
  nutrients: NutrientsInput
}

input IngredientEditInput {
  id: ID!
  name: String
  category: ID
  calories: Int
  nutrients: NutrientsInput
}

type Query {
  ingredient(id: ID!): Ingredient
  ingredients(limit: Int, skip: Int): [Ingredient]
  ingredientsByName(name: String): [Ingredient]
}

type Mutation {
  addIngredient(input: IngredientCreateInput!): Ingredient
    @auth(role: ADMIN)
  deleteIngredient(id: ID!): Boolean @auth(role: ADMIN)
  updateIngredient(input: IngredientEditInput!): Boolean @auth(role: ADMIN)
}