interface MealPlanEvent {
  _id: ID
  startTime: Date
  endTime: Date
  owner: Account
}

type MealEvent implements MealPlanEvent {
  _id: ID
  startTime: Date
  endTime: Date
  owner: Account
  mealType: String
  recipes: [Recipe]
}

type WorkoutEvent implements MealPlanEvent {
  _id: ID
  startTime: Date
  endTime: Date
  workoutType: String
  owner: Account
}

# INPUT
input MealEventAddInput {
  startTime: Date!
  endTime: Date!
  recipes: [ID]!
  mealType: String!
}

input MealEventEditInput {
  _id: ID!
  startTime: Date!
  endTime: Date!
  recipes: [ID]!
  mealType: String!
}

input WorkoutEventAddInput {
  startTime: Date!
  endTime: Date!
}

input WorkoutEventEditInput {
  _id: ID!
  startTime: Date!
  endTime: Date!
}

input MealPlanRangeInput {
  startDay: Date!
  endDay: Date!
}

type Query {
  mealPlanEvents(input: MealPlanRangeInput!): [MealPlanEvent]
}

type Mutation {
  addMealEvent(input: MealEventAddInput!): MealEvent
    @auth(role: USER)
  addWorkoutEvent(input: WorkoutEventAddInput!): WorkoutEvent
    @auth(role: USER)
  deleteEvent(id: ID!): Boolean
    @auth(role: USER)
  editMealEvent(input: MealEventEditInput!): MealEvent
    @auth(role: USER)
  editWorkoutEvent(input: WorkoutEventEditInput!): WorkoutEvent
    @auth(role: USER)
}