interface MealPlanEvent {
  id: ID
  startTime: Date
  endTime: Date
  type: String
  owner: Account
}

type MealEvent implements MealPlanEvent {
  id: ID
  startTime: Date
  endTime: Date
  type: String
  owner: Account
  mealType: String
  recipes: [Recipe]
}

type WorkoutEvent implements MealPlanEvent {
  id: ID
  startTime: Date
  endTime: Date
  type: String
  owner: Account
}

union SearchResult = MealEvent | WorkoutEvent

# INPUT
input MealEventAddInput {
  startTime: Date!
  endTime: Date!
  recipes: [ID]!
  mealType: String!
}

input WorkoutEventAddInput {
  startTime: Date!
  endTime: Date!
}

input MealPlanRangeInput {
  startDay: Date!
  endDay: Date!
}

type Query {
  findWithinRange(input: MealPlanRangeInput!): [SearchResult]
}

type Mutation {
  addMealEvent(input: MealEventAddInput!): MealEvent
    @auth(role: USER)
  addWorkoutEvent(input: WorkoutEventAddInput!): WorkoutEvent
    @auth(role: USER)
  # deleteRecipe(id: ID!): Boolean @auth(role: USER)
}